server:
  port: 8088

spring:
  #json数据配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #mybatis数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://hymbb.cn:3306/vhr?useUnicode=true&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    initialPoolSize: 3
    maxPoolSize: 50
    minPoolSize: 3
    maxIdle: 5
    type: com.alibaba.druid.pool.DruidDataSource
  #redis
  redis:
    database: 0
    host: hymbb.cn
#    host: 10.52.161.112
    port: 6379
    password: 123456
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  #缓存
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
  #邮件
  mail:
    host: smtp.qq.com
    port: 465
    username: 193533653@qq.com
    password: pclujqwpmwsqcbef
    default-encoding: UTF-8
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.debug: true
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.zhku.mh.entities

logging:
  level:
    com:
      zhku:
        mh:
          dao: debug
